# Generated by Django 4.0.1 on 2022-01-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_created_at_match_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='place_of_seats_from_col',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='place_of_seats_from_row',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='place_of_seats_to_col',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='place_of_seats_to_row',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
