# Generated by Django 4.0.1 on 2022-01-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_place_of_seats_from_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='seat_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
